# AUTOGENERATED by xylomorphic_blender_gen.py
import bpy, math, mathutils, random
from math import sin, cos, pi

# Clean slate
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.frame_start = 1
scene.frame_end = 1

# Robust view transform (avoid too-dim Filmic in headless)
try:
    scene.view_settings.view_transform = "Standard"
except Exception:
    pass

# Render engine & resolution
scene.render.engine = "CYCLES"
scene.render.resolution_x = 400
scene.render.resolution_y = 200
scene.render.resolution_percentage = 100

# PNG output (explicit)
scene.render.image_settings.file_format = 'PNG'
scene.render.image_settings.color_mode = 'RGB'
scene.render.image_settings.color_depth = '8'
scene.render.image_settings.compression = 15

if scene.render.engine == "CYCLES":
    scene.cycles.samples = 32
    # Prefer GPU if present (safe to try)
    try:
        prefs = bpy.context.preferences.addons["cycles"].preferences
        prefs.compute_device_type = "CUDA" if "CUDA" in prefs.get_device_types(bpy.context) else prefs.compute_device_type
        scene.cycles.device = "GPU"
    except Exception:
        pass
else:
    # EEVEE visibility boosts
    scene.eevee.taa_render_samples = max(8, 32)
    scene.eevee.use_gtao = True
    scene.eevee.use_bloom = True

# World light
if not scene.world:
    scene.world = bpy.data.worlds.new("World")
scene.world.use_nodes = True
wn = scene.world.node_tree
bg = wn.nodes.get("Background")
if bg:
    bg.inputs[0].default_value = (0.02, 0.03, 0.015, 1.0)
    bg.inputs[1].default_value = 1.2

# Sunlight (key)
sun_data = bpy.data.lights.new("Sun","SUN")
sun_data.energy = 4.0
sun = bpy.data.objects.new("Sun", sun_data)
bpy.context.collection.objects.link(sun)
sun.location = (8,-8,10)
sun.rotation_euler = (math.radians(60), 0, math.radians(35))

# Camera
cam_data = bpy.data.cameras.new("Camera")
cam = bpy.data.objects.new("Camera", cam_data)
bpy.context.collection.objects.link(cam)
scene.camera = cam
cam.location = (10, -12, 8)
cam.rotation_euler = (math.radians(55), 0, math.radians(40))

# Make sure camera is active for this view layer
bpy.context.view_layer.objects.active = cam
scene.camera = cam
bpy.context.view_layer.update()

# Materials
def mat_emissive(name,col=(1,1,1,1),strength=5):
    m=bpy.data.materials.new(name); m.use_nodes=True
    nt=m.node_tree
    for n in list(nt.nodes): nt.nodes.remove(n)
    e=nt.nodes.new("ShaderNodeEmission"); e.inputs[0].default_value=col; e.inputs[1].default_value=strength
    o=nt.nodes.new("ShaderNodeOutputMaterial"); nt.links.new(e.outputs[0],o.inputs[0])
    return m

def mat_pbr(name,base=(.5,.5,.5,1),rough=.6,metal=.0):
    m=bpy.data.materials.new(name); m.use_nodes=True
    p=m.node_tree.nodes.get("Principled BSDF")
    if not p:
        p = m.node_tree.nodes.new("ShaderNodeBsdfPrincipled")
        out = m.node_tree.nodes.get("Material Output") or m.node_tree.nodes.new("ShaderNodeOutputMaterial")
        m.node_tree.links.new(p.outputs["BSDF"], out.inputs["Surface"])
    p.inputs["Base Color"].default_value=base
    p.inputs["Roughness"].default_value=rough
    p.inputs["Metallic"].default_value=metal
    return m

# Scene: Pulp Conduits
fiber = mat_pbr("Fiber",(0.75,0.7,0.6,1),0.4,0)
lumen = mat_emissive("Lumen",(0.9,0.5,0.3,1),8)
for i in range(30):
    pts=[(random.uniform(-5,5),random.uniform(-5,5),z) for z in [0,1,2,3,4]]
    cu=bpy.data.curves.new("Conduit","CURVE"); cu.dimensions='3D'
    s=cu.splines.new('POLY'); s.points.add(len(pts)-1)
    for j,p in enumerate(pts): s.points[j].co=(*p,1)
    cu.bevel_depth=0.08; cu.bevel_resolution=3
    ob=bpy.data.objects.new("ConduitObj",cu)
    bpy.context.collection.objects.link(ob)
    ob.data.materials.append(fiber if i%2 else lumen)
bpy.ops.mesh.primitive_plane_add(size=20,location=(0,0,-0.2))
b=bpy.context.active_object; b.data.materials.append(mat_pbr("Base",(0.08,0.1,0.09,1),0.9,0))

scene.camera.location = (10, -14, 9)
scene.camera.rotation_euler = (math.radians(60), 0, math.radians(40))
bpy.context.view_layer.objects.active = scene.camera
bpy.context.view_layer.update()

# Save & render
blend=r"out_xylomorphic/blends/pulp_conduits-20251103T172834Z.blend"; png=r"out_xylomorphic/renders/pulp_conduits-20251103T172834Z.png"
import os
os.makedirs(os.path.dirname(blend),exist_ok=True)
os.makedirs(os.path.dirname(png),exist_ok=True)

# Ensure frame & filepath set
scene.frame_set(1)
scene.render.filepath = png

# Final safety: camera & layer update
bpy.context.view_layer.objects.active = scene.camera
bpy.context.scene.camera = scene.camera
bpy.context.view_layer.update()

bpy.ops.render.render(write_still=True)
bpy.ops.wm.save_mainfile(filepath=blend)
