#!/usr/bin/env python3
"""Render the human-readable safety index from canonical JSON records."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SAFETY = ROOT / "safety"
OUTPUT = SAFETY / "README.md"


def load(name: str) -> dict[str, Any]:
    return json.loads((SAFETY / name).read_text(encoding="utf-8"))


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    def clean(value: object) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")
    result = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    result.extend("| " + " | ".join(clean(cell) for cell in row) + " |" for row in rows)
    return result


def render() -> str:
    hazards = load("hazards.json")
    states = load("operating-states.json")
    stops = load("stop-recovery.json")
    service = load("service-maintenance.json")
    domestic = load("domestic-boundaries.json")
    manifest = load("manifests/experiment-001.json")
    manifest_data = [
        datum
        for category in manifest["categories"].values()
        for datum in category["data"]
    ]
    verified_data = sum(datum["status"] == "verified" for datum in manifest_data)
    verified_sensors = sum(item["status"] == "verified"
                           for item in manifest["required_sensors"] if item["required"])
    verified_interlocks = sum(item["status"] == "verified"
                              for item in manifest["required_interlocks"] if item["required"])

    lines = [
        "# Centerfuge Safety Records",
        "",
        "_Generated by `python3 scripts/render-safety.py`. Edit the JSON sources, not this file._",
        "",
        "The records are requirements and evidence structures, not a safety certification. "
        "A structurally valid manifest may remain blocked from operation.",
        "",
        "## Current boundary",
        "",
        f"Experiment 001 apparatus: **{'RUNNABLE' if manifest['approved_for_run'] else 'BLOCKED'}**  ",
        f"Evidence status: **{manifest['evidence_status']}**  ",
        f"Recorded blockers: **{len(manifest['blockers'])}**",
        "",
        "## Experiment 001 manifest readiness",
        "",
        "The manifest is fail-closed: every required datum must be present and verified; "
        "numeric values require tolerances; required sensors require current calibration, "
        "plausibility, and availability evidence; required interlocks require an independent "
        "fallback; and RUN requires separately recorded authorization.",
        "",
    ]
    lines += table(
        ["Evidence class", "Verified", "Required", "Current result"],
        [
            ["Apparatus data", str(verified_data), str(len(manifest_data)),
             "PASS" if verified_data == len(manifest_data) else "BLOCKED"],
            ["Safety sensors", str(verified_sensors), str(sum(
                item["required"] for item in manifest["required_sensors"])),
             "PASS" if verified_sensors == sum(
                 item["required"] for item in manifest["required_sensors"]) else "BLOCKED"],
            ["Protective interlocks", str(verified_interlocks), str(sum(
                item["required"] for item in manifest["required_interlocks"])),
             "PASS" if verified_interlocks == sum(
                 item["required"] for item in manifest["required_interlocks"]) else "BLOCKED"],
            ["Run authorization", "1" if all(manifest["run_authorization"].values()) else "0",
             "1", "PASS" if all(manifest["run_authorization"].values()) else "BLOCKED"],
        ],
    )
    lines += [
        "",
        "## Hazard register",
        "",
    ]
    lines += table(
        ["ID", "Hazard", "Severity", "Evidence", "Controls", "Open questions"],
        [[h["id"], h["title"], h["severity"], h["evidence_status"],
          str(len(h["controls"])), str(len(h["open_questions"]))] for h in hazards["hazards"]],
    )
    lines += ["", "## Operating states", ""]
    lines += table(
        ["State", "Invariant", "Access boundary"],
        [[s["id"], s["invariant"], s["access"]] for s in states["states"]],
    )
    lines += ["", "## Stop and recovery events", ""]
    lines += table(
        ["ID", "Trigger", "Class", "Hazards", "Status", "Reset"],
        [[e["id"], e["trigger"], e["stop_class"], ", ".join(e["hazards"]),
          e["status"], e["reset_authority"]] for e in stops["events"]],
    )
    lines += ["", "## Service and maintenance", ""]
    lines += table(
        ["ID", "Component", "Service class", "Access", "Status"],
        [[c["id"], c["component"], c["service_class"], c["access_state"], c["status"]]
         for c in service["components"]],
    )
    lines += ["", "## Cleaning zones", ""]
    lines += table(
        ["ID", "Zone", "Service class", "Status"],
        [[c["id"], c["zone"], c["service_class"], c["status"]]
         for c in domestic["cleaning_zones"]],
    )
    lines += ["", "## Accessibility requirements", ""]
    lines += table(
        ["ID", "Subject", "Requirement", "Status"],
        [[r["id"], r["subject"], r["requirement"], r["status"]]
         for r in domestic["accessibility_requirements"]],
    )
    lines += ["", "## Installation requirements", ""]
    lines += table(
        ["ID", "Subject", "Requirement", "Status"],
        [[r["id"], r["subject"], r["requirement"], r["status"]]
         for r in domestic["installation_requirements"]],
    )
    lines += [
        "",
        "## Canonical sources",
        "",
        "- [Normative specification](../docs/safety-maintenance-spec.md)",
        "- [Hazard register](hazards.json)",
        "- [Operating-state model](operating-states.json)",
        "- [Stop and recovery matrix](stop-recovery.json)",
        "- [Service and maintenance register](service-maintenance.json)",
        "- [Domestic boundaries](domestic-boundaries.json)",
        "- [Experiment 001 manifest](manifests/experiment-001.json)",
        "- [Schemas](schemas/)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/render-safety.py",
                  file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current.")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
