#!/usr/bin/env python3
"""
make_generator.py — emit a new headless bpy generator from an rsvp preset.

Usage:
    python make_generator.py NAME [--preset PRESET] [--output-dir DIR]

Examples:
    python make_generator.py tower --preset make_landscape_operators
    python make_generator.py forest --preset make_tree_operators
"""

from __future__ import annotations
import argparse
from pathlib import Path

VALID_PRESETS = [
    "make_default_rsvp_field",
    "make_tree_operators",
    "make_landscape_operators",
    "make_seam_operators",
]

TEMPLATE = '''\
#!/usr/bin/env python3
"""
generate_{name}.py — headless Blender generator.
Preset: {preset}
Auto-generated by make_generator.py. Extend the USER LOGIC section below.
"""

from __future__ import annotations
import sys
import argparse
import random


def parse_args() -> argparse.Namespace:
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = []
    p = argparse.ArgumentParser(description="RSVP generator: {name}")
    p.add_argument("--output", required=True, help="Path to output .blend file")
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args(argv)


args = parse_args()

import bpy  # noqa: E402
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rsvp  # noqa: E402

rng = random.Random(args.seed)

# --- field setup ---
ops = rsvp.{preset}()
print(f"[{name}] preset={preset!r}  seed={{args.seed}}")

# --- scene reset ---
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

# -----------------------------------------------------------------------
# USER LOGIC — replace this section with your bpy geometry code.
# ops contains the field callables returned by {preset}().
# Example for tree preset:
#   path = rsvp.trace_growth_path((0,0,0), ops["v_field"])
# Example for landscape preset:
#   hmap = rsvp.sample_height_map(ops["terrain"], 64, 64)
# -----------------------------------------------------------------------


# --- camera (placeholder) ---
cam_data = bpy.data.cameras.new("Camera")
cam_obj = bpy.data.objects.new("Camera", cam_data)
bpy.context.scene.collection.objects.link(cam_obj)
cam_obj.location = (4.0, -4.0, 3.0)
cam_obj.rotation_euler = (1.1, 0.0, 0.785)
bpy.context.scene.camera = cam_obj

bpy.ops.wm.save_as_mainfile(filepath=args.output)
print(f"[{name}] saved to {{args.output}}")
'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Emit a new rsvp generator script")
    parser.add_argument("name", help="Generator name, e.g. tower or forest")
    parser.add_argument(
        "--preset",
        default="make_default_rsvp_field",
        choices=VALID_PRESETS,
        help="rsvp preset function to wire in",
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory to write the new generator (default: current dir)",
    )
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = out_dir / f"generate_{args.name}.py"

    fname.write_text(
        TEMPLATE.format(name=args.name, preset=args.preset),
        encoding="utf-8",
    )
    fname.chmod(0o755)
    print(f"[make_generator] wrote {fname}")


if __name__ == "__main__":
    main()
